name: Bug Report
description: Report broken links, incorrect info, or layout glitches
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - nota9x
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        Thank you for taking the time to report a bug. Please fill out the form below.
  
  - type: textarea
    id: what-is-broken
    attributes:
      label: "1. What is broken?"
      description: "Describe the issue clearly. (e.g., 'DNS setup command is wrong,' 'Mobile menu glitch,' 'Dead link on Home page')"
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: input
    id: affected-page
    attributes:
      label: "2. Affected Page / Section"
      description: "Which URL or section is this happening on?"
      placeholder: "e.g., /self-hosting/dns, Introduction"
    validations:
      required: true
  
  - type: input
    id: browser-device
    attributes:
      label: "3. Browser & Device"
      description: "What are you using?"
      placeholder: "e.g., Chrome on School Chromebook, Safari on iPhone, Firefox on Windows"
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "4. Steps to Reproduce"
      description: "How can we make this happen?"
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true
  
  - type: textarea
    id: screenshots-logs
    attributes:
      label: "5. Screenshots / Logs (Optional)"
      description: "If you see a layout issue or error message, a screenshot helps a lot. If a command failed, paste the output here."
      placeholder: Paste screenshots or logs here
    validations:
      required: false
  
  - type: checkboxes
    id: confirmation
    attributes:
      label: "Confirmation"
      options:
        - label: "I have searched existing issues to ensure this bug hasn't already been reported."
          required: true
